version: '3.9'
name: csv-to-db-project

services:
  mariadb:
    image: mariadb:11.7
    container_name: csv-to-db-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./data/mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:17-alpine3.21
    container_name: csv-to-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

